# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleWithCocoaPods' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExampleWithCocoaPods
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end
